name: Build lambda layer
on:
  workflow_dispatch:

jobs:
  lambda:
    name: Create layer for lambda
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Build layer
      run: make aws-lambda-x64.zip

    - name: Add to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PKG_VERSION=v$(npm pkg get version | tr -d '"')
        echo $PKG_VERSION
        gh release upload $PKG_VERSION aws-lambda-x64.zip
