name: Publish to NPM
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15
        registry-url: 'https://registry.npmjs.org'

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish

  lambda:
    name: Create layer for lambda
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, arm64]
    runs-on: ${{ matrix.arch == 'x86' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Build layer
      run: |
        docker run -v ./arch/lambda:/opt -v .:/mnt amazonlinux:2023 bash /opt/build-layer.sh

    - name: Add to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PKG_VERSION=v$(npm pkg get version | tr -d '"')
        gh release upload $PKG_VERSION aws-lambda-*.zip
