name: Publish to NPM
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15
        registry-url: 'https://registry.npmjs.org'

    - name: Add hashes to package.json
      run: |
        npm ci
        node lib/prebuild.mjs snapshot
        npm pkg get prebuild

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish
