name: Run tests
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  run-tests:
    name: Rebuild & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-22.04
        node:
          - 18
          - 24

    steps:
    - name: Enable long paths (Windows only)
      if: ${{ matrix.os == 'windows-latest' }}
      run: git config --system core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'

    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Use Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build module
      run: make optimized

    - name: Run tests
      run: |
        npm test --verbose
